steps:
#step 1
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/S-O-L-A-R/rms-ms.git']

- name: 'gcr.io/cloud-builders/git'
  args: ['checkout', 'deployment']
  dir: 'rms-ms'


- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']

- name: 'gcr.io/cloud-builders/mvn'
  args: ['package']


#step 2
- name: gcr.io/cloud-builders/docker
  args: [
    'build',
    '-t',
    'gcr.io/$PROJECT_ID/rms-ms:$BRANCH_NAME',
    '-t',
    'gcr.io/$PROJECT_ID/rms-ms:latest',
    '.'
  ]

#step 3
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=solar-cluster'

#step 4
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
    'set',
    'image',
    'deployment',
    'rms-ms',
    'rms-ms=gcr.io/$PROJECT_ID/rms-ms:$BRANCH_NAME'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=solar-cluster'
  
# push images to Google Container Registry with tags
images: [
  'gcr.io/$PROJECT_ID/rms-ms:$BRANCH_NAME',
  'gcr.io/$PROJECT_ID/rms-ms:latest'
]