apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: rms-ms
  name: rms-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      run: rms-ms
  template:
    metadata:
      labels:
        run: rms-ms
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: firebase-key
      containers:
      - image: gcr.io/vaulted-channel-252309/rms-ms:latest
        name: rms-ms
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        - name: line.channel-access-token
          valueFrom:
            secretKeyRef:
              name: rms-ms
              key: line.channel-access-token
